//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagment.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permession
    {
        public Permession()
        {
            this.UserGroupPermessions = new HashSet<UserGroupPermession>();
        }
    
        public int ID { get; set; }
        public string PermessionName { get; set; }
        public string PropertyName { get; set; }
    
        public virtual ICollection<UserGroupPermession> UserGroupPermessions { get; set; }
    }
}
