//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagment.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupPermession
    {
        public int Id { get; set; }
        public bool ValueX { get; set; }
    
        public virtual Permession Permession { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
