//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagment.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.UserGroupPermessions = new HashSet<UserGroupPermession>();
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
    
        public virtual ICollection<UserGroupPermession> UserGroupPermessions { get; set; }
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
